export const colors = {
  completed: "bg-green-600",
  active: "bg-yellow-600",
  newTask: "bg-blue-600",
  failed: "bg-red-600",
};

const employees = [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    email: "employee1@example.com",
    password: "123",
    tasks: [
      {
        title: "Complete report",
        description: "Finish the quarterly financial report.",
        date: "2024-10-20",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        bgColor: "bg-red-600",
        textColor: "text-red-600",
        priority: "high",
      },
      {
        title: "Team meeting",
        description: "Attend the team meeting to discuss project progress.",
        date: "2024-10-21",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        bgColor: "bg-blue-600",
        textColor: "text-blue-600",
        priority: "medium",
      },
      {
        title: "Fix bugs",
        description: "Resolve bugs reported in the ticketing system.",
        date: "2024-10-22",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        bgColor: "bg-green-600",
        textColor: "text-green-600",
        priority: "high",
      },
    ],
    taskCount: {
      active: 2,
      new: 2,
      completed: 1,
      failed: 0,
    },
  },
  {
    id: 2,
    firstName: "Jane",
    lastName: "Smith",
    email: "employee2@example.com",
    password: "123",
    tasks: [
      {
        title: "Design homepage",
        description: "Create the design for the new homepage.",
        date: "2024-10-19",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        bgColor: "bg-yellow-600",
        textColor: "text-yellow-600",
        priority: "medium",
      },
      {
        title: "Client meeting",
        description: "Meet with client to discuss project requirements.",
        date: "2024-10-20",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        bgColor: "bg-purple-600",
        textColor: "text-purple-600",
        priority: "high",
      },
      {
        title: "Test feature",
        description: "Test the newly implemented login feature.",
        date: "2024-10-21",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        bgColor: "bg-pink-600",
        textColor: "text-pink-600",
        priority: "medium",
      },
    ],
    taskCount: {
      active: 2,
      new: 2,
      completed: 1,
      failed: 0,
    },
  },
  {
    id: 3,
    firstName: "Michael",
    lastName: "Johnson",
    email: "employee3@example.com",
    password: "123",
    tasks: [
      {
        title: "Prepare presentation",
        description: "Create slides for the upcoming project demo.",
        date: "2024-10-23",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        bgColor: "bg-teal-600",
        textColor: "text-teal-600",
        priority: "high",
      },
      {
        title: "Code review",
        description: "Review code submitted by the team.",
        date: "2024-10-20",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        bgColor: "bg-orange-600",
        textColor: "text-orange-600",
        priority: "medium",
      },
    ],
    taskCount: {
      active: 1,
      new: 1,
      completed: 1,
      failed: 0,
    },
  },
  {
    id: 4,
    firstName: "Emily",
    lastName: "Davis",
    email: "employee4@example.com",
    password: "123",
    tasks: [
      {
        title: "Database migration",
        description: "Migrate the database to the new server.",
        date: "2024-10-22",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        bgColor: "bg-cyan-600",
        textColor: "text-cyan-600",
        priority: "high",
      },
      {
        title: "Create API",
        description: "Build API for the new mobile app.",
        date: "2024-10-23",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        bgColor: "bg-indigo-600",
        textColor: "text-indigo-600",
        priority: "medium",
      },
      {
        title: "Bug fixes",
        description: "Fix bugs found in the production system.",
        date: "2024-10-19",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        bgColor: "bg-lime-600",
        textColor: "text-lime-600",
        priority: "medium",
      },
    ],
    taskCount: {
      active: 2,
      new: 2,
      completed: 1,
      failed: 0,
    },
  },
  {
    id: 5,
    firstName: "David",
    lastName: "Brown",
    email: "employee5@example.com",
    password: "123",
    tasks: [
      {
        title: "Write documentation",
        description: "Document the API endpoints for the team.",
        date: "2024-10-18",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        bgColor: "bg-gray-600",
        textColor: "text-gray-600",
        priority: "medium",
      },
      {
        title: "Update software",
        description: "Upgrade the company's software to the latest version.",
        date: "2024-10-21",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        bgColor: "bg-emerald-600",
        textColor: "text-emerald-600",
        priority: "high",
      },
      {
        title: "Monitor systems",
        description: "Keep track of system health and uptime.",
        date: "2024-10-22",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        bgColor: "bg-fuchsia-600",
        textColor: "text-fuchsia-600",
        priority: "medium",
      },
    ],
    taskCount: {
      active: 2,
      new: 1,
      completed: 1,
      failed: 0,
    },
  },
];

const admin = [
  {
    id: 1,
    firstName: "Sarah",
    lastName: "Wilson",
    email: "admin@example.com",
    password: "123",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));

  return { employees, admin };
};
